
-- Grooty Store V3 - esquema inicial para Supabase
-- Ejecutar en Supabase SQL Editor cuando se decida conectar el frontend.
-- Esta versión NO se ejecuta automáticamente y no contiene contraseñas.

create extension if not exists pgcrypto;

create table if not exists public.brands (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  slug text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sku text unique,
  brand_id uuid references public.brands(id),
  title text not null,
  slug text not null unique,
  condition text not null check (condition in ('Sellado','Open')),
  sale_type text not null check (sale_type in ('venta','preventa')),
  price numeric(10,2) not null check (price >= 0),
  reservation_price numeric(10,2),
  stock integer default null check (stock is null or stock >= 0),
  published boolean not null default true,
  archived boolean not null default false,
  revision integer not null default 1 check (revision >= 0),
  franchise text,
  character_name text,
  includes_text text,
  box_note text,
  description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  position integer not null default 0,
  source_type text not null default 'grooty',
  source_note text,
  created_at timestamptz not null default now()
);

create table if not exists public.hero_slides (
  id uuid primary key default gen_random_uuid(),
  product_id bigint references public.products(id) on delete set null,
  headline text,
  subheadline text,
  position integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.analytics_events (
  id bigint generated always as identity primary key,
  event_name text not null,
  product_id bigint references public.products(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.hero_slides enable row level security;
alter table public.analytics_events enable row level security;

drop policy if exists "public read brands" on public.brands;
create policy "public read brands" on public.brands for select using (active = true);

drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (published = true and archived = false);

drop policy if exists "public read product images" on public.product_images;
create policy "public read product images" on public.product_images for select using (exists (select 1 from public.products p where p.id = product_id and p.published = true and p.archived = false));

drop policy if exists "public read hero" on public.hero_slides;
create policy "public read hero" on public.hero_slides for select using (active = true);

-- analytics_events no tiene lectura pública.
-- Crear inserción controlada mediante Edge Function o endpoint server-side antes de producción.

-- V5: stock desconocido se representa con NULL; no se cambian valores existentes.
alter table public.products alter column stock drop not null;
alter table public.products alter column stock set default null;
alter table public.products add column if not exists revision integer not null default 1;

-- Las escrituras siguen bloqueadas para visitantes. El backend debe comprobar
-- owner/admin, CSRF y revision antes de usar su conexión privada.
-- Nunca incluyas service_role ni una conexión PostgreSQL en el frontend.

-- Configuración pública de contacto, destacados y contenido editorial.
-- No guardar secretos, contraseñas ni tokens dentro de value.
create table if not exists public.store_settings (
  key text primary key check (key = 'storefront'),
  value jsonb not null default '{}'::jsonb check (jsonb_typeof(value) = 'object'),
  revision integer not null default 1 check (revision > 0),
  updated_at timestamptz not null default now()
);
alter table public.store_settings enable row level security;
drop policy if exists "public read storefront settings" on public.store_settings;
create policy "public read storefront settings" on public.store_settings for select using (key = 'storefront');
-- Las escrituras se realizan únicamente desde el backend autorizado.
