-- NUEVO PROYECTO Supabase. No ejecutar sobre la base actual sin comparar el esquema.
-- Solo catálogo público; no cuentas de administrador ni pedidos expuestos.
begin;
create table public.productos (
 id bigint generated by default as identity primary key,
 sku text not null unique,
 marca text not null check (length(trim(marca)) > 0),
 titulo text not null check (length(trim(titulo)) between 1 and 250),
 estado text not null check (estado in ('Sellado','Open')),
 precio numeric(12,2) not null check (precio >= 0),
 precio_reserva numeric(12,2) check (precio_reserva >= 0 and precio_reserva <= precio),
 tipo text not null default 'venta' check (tipo in ('venta','preventa')),
 stock integer check (stock >= 0), -- NULL = desconocido; nunca inventar existencias
 publicado boolean not null default false,
 archivado boolean not null default false,
 creado_en timestamptz not null default now(),
 actualizado_en timestamptz not null default now()
);
create table public.imagenes_producto (
 id bigint generated always as identity primary key,
 producto_id bigint not null references public.productos(id) on delete cascade,
 url text not null check (url ~ '^https://'),
 posicion integer not null check (posicion >= 0),
 unique(producto_id,posicion)
);
create index productos_catalogo_idx on public.productos(tipo,marca,actualizado_en desc) where publicado and not archivado;
create function public.grooty_actualizar_fecha() returns trigger language plpgsql set search_path = '' as $$
begin new.actualizado_en = now(); return new; end; $$;
create trigger productos_actualizar_fecha before update on public.productos for each row execute function public.grooty_actualizar_fecha();
alter table public.productos enable row level security;
alter table public.imagenes_producto enable row level security;
revoke all on public.productos,public.imagenes_producto from anon,authenticated;
grant select on public.productos,public.imagenes_producto to anon,authenticated;
create policy catalogo_publicado on public.productos for select to anon,authenticated using (publicado and not archivado);
create policy imagenes_publicadas on public.imagenes_producto for select to anon,authenticated using (exists(select 1 from public.productos p where p.id=producto_id and p.publicado and not p.archivado));
-- No políticas INSERT/UPDATE/DELETE para visitantes ni usuarios autenticados.
-- Las escrituras del backend requieren comprobar el rol administrador antes de usar service_role.
commit;
