import {esc,$} from '../lib/dom.js';
import {commerceRequest} from '../lib/commerce-client.js';
import {money} from '../lib/format.js';
export const operations={
 render(){return {title:'Operaciones · Grooty Store',description:'Panel privado de pedidos y autorizaciones.',html:`<section class="container commerce-wrap"><p class="eyebrow">Grooty / Operaciones</p><h1 class="h-page">Control comercial</h1><p class="page-sub">Datos del servidor. Las acciones disponibles dependen de tu rol y MFA.</p><div class="commerce-actions"><a class="btn btn-secondary" href="/admin">Catálogo</a><a class="btn btn-secondary" href="/cuenta">Cuenta y MFA</a></div><div data-operations><p>Cargando permisos…</p></div><p role="status" data-operation-status></p></section>`};},
 mount(root){const ac=new AbortController(),target=$('[data-operations]',root),status=$('[data-operation-status]',root);let session;
  const api=(p,o={})=>commerceRequest(p,{...o,signal:ac.signal});
  async function load(){try{
   session=await api('/account/session');if(!session.mfaVerified||!['ADMIN','SUPER_ADMIN','ORDER_MANAGER'].includes(session.user.role))throw Error('Este panel requiere permiso de operaciones y MFA.');
   const {orders}=await api('/admin/orders');if(ac.signal.aborted)return;
   target.innerHTML=`<div class="commerce-grid"><article class="commerce-panel"><h2>Pedidos</h2><p>Hasta 100 pedidos recientes.</p>${orders.length?orders.map(o=>`<article class="commerce-order"><h3>${esc(o.id.slice(0,8))}</h3><p>${esc(o.status)} · ${money(Number(o.total_cents)/100)}</p>${({PAID:'PROCESSING',PROCESSING:'SHIPPED',SHIPPED:'DELIVERED'})[o.status]?`<button class="btn btn-secondary" data-order="${o.id}" data-state="${({PAID:'PROCESSING',PROCESSING:'SHIPPED',SHIPPED:'DELIVERED'})[o.status]}">Marcar ${esc(({PAID:'PROCESSING',PROCESSING:'SHIPPED',SHIPPED:'DELIVERED'})[o.status])}</button>`:''}</article>`).join(''):'<p>No hay pedidos registrados.</p>'}</article><article class="commerce-panel"><h2>Figuras a pedido</h2><div data-requests>Cargando…</div></article>${session.user.role==='SUPER_ADMIN'?'<article class="commerce-panel"><h2>Autorizaciones</h2><p>Reautenticación reciente y MFA son obligatorios. Selecciona una identidad ya verificada; autorizar cierra sus sesiones.</p><div data-identities>Cargando…</div></article>':''}</div>`;
   try{const {requests}=await api('/admin/requests');if(ac.signal.aborted)return;$('[data-requests]',root).innerHTML=requests.length?requests.map(r=>`<article class="commerce-order"><h3>${esc(r.details.character)}</h3><p>${esc(r.status)} · ${esc(r.details.brand)}</p>${['SUBMITTED','REVIEWING'].includes(r.status)?`<form data-quote="${r.id}"><label class="admin-field">Cotización (S/)<input type="number" name="price" min="0.01" step="0.01" max="999999" required></label><button class="btn btn-secondary">Enviar cotización</button></form>`:''}</article>`).join(''):'<p>No hay solicitudes.</p>';}catch(error){$('[data-requests]',root).textContent=error.message;}
   if(session.user.role==='SUPER_ADMIN')try{const {identities}=await api('/admin/identities');if(ac.signal.aborted)return;$('[data-identities]',root).innerHTML=`<form data-authorization><label class="admin-field">Identidad<select name="identityId">${identities.map(i=>`<option value="${i.id}">${esc(i.email)} · ${esc(i.provider)} · ${esc(i.role)}</option>`).join('')}</select></label><label class="admin-field">Rol<select name="role">${['CATALOG_MANAGER','ORDER_MANAGER','ADMIN','SUPER_ADMIN'].map(r=>`<option>${r}</option>`).join('')}</select></label><label class="admin-field">Acción<select name="status"><option value="ACTIVE">Autorizar</option><option value="REVOKED">Revocar</option></select></label><button class="btn btn-primary">Aplicar autorización</button></form>`;}catch(error){$('[data-identities]',root).textContent=error.message;}
  }catch(error){if(!ac.signal.aborted){target.innerHTML='<a class="btn btn-primary" href="/cuenta">Verificar cuenta y MFA</a>';status.textContent=error.message;}}}
  root.addEventListener('click',async e=>{const b=e.target.closest('[data-order]');if(!b)return;b.disabled=true;try{await api('/admin/orders/'+b.dataset.order,{method:'PATCH',body:{status:b.dataset.state}});status.textContent='Estado actualizado.';await load();}catch(error){status.textContent=error.message;}finally{b.disabled=false;}},{signal:ac.signal});
  root.addEventListener('submit',async e=>{if(!e.target.matches('[data-quote],[data-authorization]'))return;e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;try{
   const values=Object.fromEntries(new FormData(e.target));if(e.target.matches('[data-quote]')){const price=values.price;if(!/^\d{1,6}(\.\d{1,2})?$/.test(price))throw Error('Importe inválido.');await api('/admin/requests/'+e.target.dataset.quote+'/quote',{method:'POST',body:{quoteCents:Math.round(Number(price)*100)}});}else await api('/admin/authorizations',{method:'POST',body:values});status.textContent='Cambio confirmado por el servidor.';await load();
  }catch(error){status.textContent=error.message;}finally{b.disabled=false;}},{signal:ac.signal});load();return ()=>ac.abort();
 }
};
